name: Litmus-CI
on:
  issue_comment:
    types: [created, edited]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Golang
        if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run-e2e')
        uses: actions/setup-go@v2

      - name: Build docker image
        if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run-e2e')
        run: 	sudo docker build . -f build/ansible-runner/Dockerfile -t uditgaurav/demo-litmus-e2e:v1

      - name: Installing Prerequisites
        if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run-e2e')
        run: |
          export GOPATH=$HOME/go/
          mkdir -p $HOME/go/src/github.com/mayadata-io/
          cd /home/runner/go/src/github.com/mayadata-io/
          git clone https://github.com/mayadata-io/chaos-ci-lib
          kind create cluster --loglevel debug --wait=5m
          kubectl cluster-info --context kind-kind
          kind load docker-image uditgaurav/demo-litmus-e2e:v1
          go test chaos-ci-lib/tests/install-litmus_test.go -v -count=1
          kubectl create -f https://raw.githubusercontent.com/uditgaurav/litmuschaos/master/app/nginx.yml
          sleep 5

      - name: Running Litmus pod delete chaos experiment
        if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run-e2e-pod-delete')
        uses: mayadata-io/github-chaos-actions@v0.1.0
        env:
          INSTALL_LITMUS: true
          EXPERIMENT_NAME: pod-delete
          EXPERIMENT_IMAGE: uditgaurav/demo-litmus-e2e:ci        
          LITMUS_CLEANUP: true
                    
      - name: Running app
        if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run-e2e-all')
        run: |
          echo "Hello all"

