name: Litmus-CI
on:
  issue_comment:
    types: [created, edited]
jobs:
  tests:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run-e2e')
    runs-on: ubuntu-latest
    steps:

      # - name: Setup Golang
      #   uses: actions/setup-go@v2

      - name: The e2e Starts
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: "${{ github.event.comment.id }}"
          body: |
            ****
            The e2e test has been started please wait for the test result ...

      - name: Running git checkout
        uses: actions/checkout@v2

      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: uditgaurav/docker-build
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: build/ansible-runner/Dockerfile
          tags: "ci"

      - name: Getting docker images
        run: |
          sudo docker images

      - name: Installing Prerequisites
        run: |
          kind create cluster --loglevel debug --wait=5m
          kubectl cluster-info --context kind-kind
          kind get kubeconfig --internal >$HOME/.kube/config
          kubectl create -f https://raw.githubusercontent.com/uditgaurav/litmuschaos/master/app/nginx.yml
          sleep 10
          kubectl get nodes

      - name: Saving the image 
        run: |
          kubectl get nodes   
          kind load docker-image --name=kind uditgaurav/docker-build:ci

      - name: Spin up a pod with the given image
        run: |
          kubectl apply -f https://raw.githubusercontent.com/uditgaurav/litmuschaos/master/app/nginx.yml
          sleep 60

      - name: Setting up kubeconfig ENV for Github Chaos Action
        run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)

      - name: Running Litmus pod delete chaos experiment
        if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run-e2e-pod-delete')
        uses: mayadata-io/github-chaos-actions@v0.1.0
        env:
          INSTALL_LITMUS: true
          EXPERIMENT_NAME: pod-delete
          EXPERIMENT_IMAGE: uditgaurav/docker-build:ci
          LITMUS_CLEANUP: true
                    
      - name: Running app
        if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run-e2e-all')
        run: |
          echo "Hello all"

      - name: The job has succeeded
        if: ${{ success() }}      
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: "${{ github.event.comment.id }}"
          body: |  
            **Test Result:** All tests are passed
          reactions: hooray

      - name: The job has failed
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: "${{ github.event.comment.id }}"
          body: |
            **Test Failed:** Some tests are failed please check
          reactions: confused        
